{
    'name': "Harleys Customization",

    'summary': "Harleys Customization",
    "version": "19.0.0.0.1",
    'author': "Harleys",
    'description': """
           Harleys Customization
    """,
    'category': 'Customizations',
    'depends': ['base','web', 'stock','mrp', 'sale_mrp', 'helpdesk', 'product_expiry', 'account', 'purchase'],
    'data': [
        'security/security_group.xml',
        'security/ir.model.access.csv',
        'security/helpdesk_tag_portal_access.xml',
        'views/indent_request_views.xml',
        'views/indent_request_template_views.xml',
        'views/res_users_views.xml',
        'views/res_config_settings_views.xml',
        'data/indent_request_sequence.xml',
        'data/indent_request_cron.xml',
        'wizard/indent_request_line_make_manufacturing_orders_views.xml',
        'wizard/merge_mrp_production_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/contact_views.xml',
        'views/mrp_bom_views.xml',
        'views/mrp_production_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
        'views/service_type_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_portal_template.xml',
        'views/purchase_views.xml',
        'views/stock_quant_views.xml',
        'views/stock_scrap_views.xml',
        'views/account_move_views.xml',
        'views/stock_location_views.xml',
        'reports/manufacturing_order_lines_views.xml',
        'reports/report_deliveryslip_template.xml',
        'reports/picking_report_template.xml',
        'wizard/mol_internal_transfer_views.xml',
        'wizard/mo_internal_transfer_views.xml',
        'wizard/indent_zero_qty_warning_views.xml',
        'wizard/indent_close_confirm_views.xml',
        'wizard/stock_picking_close_confirm_views.xml',
        'wizard/stock_picking_qty_mismatch_confirm_views.xml',
        
    ],
    'assets': {
        'web.assets_backend': [
            'harleys_customization/static/src/js/searchable_x2many.js',
            'harleys_customization/static/src/js/location_gate.js',
            'harleys_customization/static/src/js/stock_move_line_rows.js',
            'harleys_customization/static/src/js/stock_move_line_row_field.js',
            'harleys_customization/static/src/js/stock_move_line_batch_field.js',
            'harleys_customization/static/src/js/stock_move_line_batch_quickcreate.js',
            'harleys_customization/static/src/js/stock_scrap_list.js',
            'harleys_customization/static/src/js/stock_quant_new_confirm.js',
            'harleys_customization/static/src/xml/searchable_x2many.xml',
            'harleys_customization/static/src/xml/location_gate_list_view.xml',
            'harleys_customization/static/src/xml/stock_move_line_row_field.xml',
            'harleys_customization/static/src/xml/stock_move_line_batch_field.xml',
            'harleys_customization/static/src/xml/stock_move_line_batch_quickcreate.xml',
            'harleys_customization/static/src/xml/loading_indicator.xml',
            'harleys_customization/static/src/scss/searchable_x2many.scss',
            'harleys_customization/static/src/scss/location_gate.scss',
            'harleys_customization/static/src/scss/stock_picking_close_confirm.scss',
            'harleys_customization/static/src/scss/stock_picking_operations.scss',
            'harleys_customization/static/src/scss/loading_indicator.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
