from . import indent_request
from . import indent_request_templates
from . import res_partner
from . import product_template
from . import stock_picking
from . import mrp
from . import mrp_bom
from . import service_type
from . import helpdesk_ticket
from . import stock_move_line
from . import stock_warehouse